### ISSUE TITLE
Splitter and Alternator Crash with Chest

### ISSUE THREAD

**Issue by 1a2s3d4f1** [Zundrel/Conveyance#3]
![2019-12-30_20.33.10.png](https://i.loli.net/2019/12/30/A4EBsRaxYW18roQ.png)
![2019-12-30_20.27.57.png](https://i.loli.net/2019/12/30/dWYHwzXem3jCL71.png)
crash report:
https://paste.ubuntu.com/p/dMC5Mx6PhZ/
https://paste.ubuntu.com/p/v2Rvfx3qQ3/
Minecraft:1.15.1

**Comment by Zundrel** [comment]
I'm looking into this crash now, sorry for the long wait.

**Comment by Zundrel** [comment]
This has been fixed in the latest build, going out on CurseForge as we speak.
